name: build and deploy ingest_lib

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        python-version: [3.11]
        poetry-version: [1.2.2]

    steps:
    - name: code checkout
      uses: actions/checkout@v3

    - name: setup python v${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}


    - name: install poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: update version in pyproject.toml
      env:
        POETRY_NO_INTERACTION: 1
      run: |
        cd package1
        poetry version "${{ github.ref_name }}"
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "ppowell@lightboxre.com"
        git add pyproject.toml
        git commit -m "auto - bump project version to ${{ github.ref_name }}"

    - name: push changes
      #env:
      #   GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      run: |
        git push
    # git push https://${{ env.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
    
