name: Manual Build Event

on:
   workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'prepatch'
        type: choice
        options:
        - 'patch'
        - 'minor'
        - 'major'
        - 'prepatch'
        - 'preminor'
        - 'premajor'
        - 'prerelease'
jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        python-version: [3.11]
        poetry-version: [1.2.2]

    steps:
    - name: what version
      run: |
        echo ${{ github.event.inputs.build_type }}
    - name: Code checkout
      uses: actions/checkout@v4
      #with: 
       #  persist-credentials: false

    - name: git_status
      run: |
         git status
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT     
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}


    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.1.6
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Bump Version
      env: 
        CI_COMMIT_MESSAGE: CI Version Bump
        CI_COMMIT_AUTHOR: CI
      run: |
        cd package1
        poetry version ${{ github.event.inputs.build_type }}
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "locdata-dataingest-service@lightboxre.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
    
